# Generated by Django 4.2.16 on 2025-06-22 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('key_word', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcontent',
            options={'verbose_name': '블로그 콘텐츠', 'verbose_name_plural': '블로그 콘텐츠'},
        ),
        migrations.AlterModelOptions(
            name='morphemeanalysis',
            options={'verbose_name': '형태소 분석 결과', 'verbose_name_plural': '형태소 분석 결과'},
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='morphemeanalysis',
            name='morpheme_type',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='char_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='is_optimized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='key_word.keyword'),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='mobile_formatted_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='morphemeanalysis',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morpheme_analyses', to='content.blogcontent'),
        ),
        migrations.AlterField(
            model_name='morphemeanalysis',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='morphemeanalysis',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='morphemeanalysis',
            name='morpheme',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='morphemeanalysis',
            unique_together={('content', 'morpheme')},
        ),
    ]
